services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: taskmanagement-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1455:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./Database:/workspace/Database

volumes:
  sqlserver-data:
